services:
    _defaults:
        public: true
        autowire: true

    GraphQLByPoP\GraphQLReques\PersistedQueries\GraphQLPersistedQueryManagerInterface:
        class: \GraphQLByPoP\GraphQLReques\PersistedQueries\GraphQLPersistedQueryManager

    GraphQLByPoP\GraphQLRequest\Hooks\:
        resource: '../src/Hooks/*'
